let
    // 1. Initial Source Loading
    SourcePath = Excel.CurrentWorkbook(){[Name="MXFile"]}[Content]{0}[Column1],
    ExternalWorkbook = Excel.Workbook(File.Contents(SourcePath), null, true),
    Sheet1_Sheet = ExternalWorkbook{[Item="Sheet1", Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),

    // 2. Merging and Filtering Shortlisted Clients
    #"Merged Queries" = Table.NestedJoin(#"Promoted Headers", {"COUNTERPART"}, ListofACtoAddFrmMurex, {"Column1"}, "ListofACtoAddFrmMurex", JoinKind.Inner),
    #"Expanded Client" = Table.ExpandTableColumn(#"Merged Queries", "ListofACtoAddFrmMurex", {"Column2"}, {"Client"}),

    // 3. Remove unnecessary columns
    #"Removed Initial Columns" = Table.RemoveColumns(#"Expanded Client",{ /* … same as before … */ }),

    // 4. Renaming and Filtering
    #"Renamed Base" = Table.RenameColumns(#"Removed Initial Columns",{
        {"INSTRUMENT", "CcyPair"}, {"BRW_NOMU1", "BaseCcy"}, {"QTY.NOMINAL", "BaseNot"}, 
        {"BRW_NOMU2", "CounterCcy"}, {"BRW_NOM2", "CounterNot"}, {"XPOPTFPRIC", "Strike"}, 
        {"XPOPTCUTOF", "Cut"}
    }),
    #"Filtered Options" = Table.SelectRows(#"Renamed Base", each [#"C/P"] = "C" or [#"C/P"] = "P"),

    // 5. Currency-based Division
    #"Divide Notionals" = Table.TransformRows(#"Filtered Options", (r) => 
        let
            divBase = if r[BaseCcy] <> "XAG" and r[BaseCcy] <> "XAU" then Number.From(r[BaseNot]) / 1000 else Number.From(r[BaseNot]),
            divCounter = if r[CounterCcy] <> "XAG" and r[CounterCcy] <> "XAU" then Number.From(r[CounterNot]) / 1000 else Number.From(r[CounterNot])
        in
            Record.TransformFields(r, {{"BaseNot", each divBase}, {"CounterNot", each divCounter}})
    ),
    #"Converted Divided" = Table.FromRecords(#"Divide Notionals", Value.Type(#"Filtered Options")),

    // 6. Flip Logic
    /* … unchanged … */

    // 7. Combination Logic for FX_KOFW
    /* … unchanged … */

    // 8. Final Struct Logic
    /* … unchanged … */

    // 9. Final Header Mapping
    #"Mapped Headers" = Table.RenameColumns(#"Final Table",{
        {"Client", "Customer"}, {"CcyPair", "CCYpair"}, {"BaseCcy", "Ccy"}, 
        {"BaseNot", "Notional"}, {"Strike", "Active Strike"}, {"BARRIER0", "KO/Pivot"}, 
        {"EXPIRY", "Expiry"}, {"TRN.DATE", "Trade Date"}, {"TP_STATUS", "Live"}, 
        {"STRUCT_ID", "FXDC Ref"}, {"FlippedIndicator", "Comment"}
    }),

    // 10. Revised Expiry Correction Logic
    Today = Date.From(DateTime.LocalNow()),
    TodayMonth = Date.Month(Today),

    #"Apply Date Fix" =
        Table.TransformColumns(
            #"Mapped Headers",
            {
                // Trade Date: unchanged
                {
                    "Trade Date",
                    each 
                        if _ is text then Date.FromText(_, "en-GB")
                        else if _ is number or _ is date then Date.From(_)
                        else _,
                    type date
                },

                // Expiry: safer correction
                {
                    "Expiry",
                    each
                        let
                            conv =
                                if _ is date then _
                                else if _ is number then Date.From(_)
                                else if _ is text then try Date.FromText(_, "en-GB") otherwise null
                                else null,

                            result =
                                if conv <> null then
                                    let
                                        d        = conv,
                                        srcDay   = Date.Day(d),
                                        srcMonth = Date.Month(d),
                                        srcYear  = Date.Year(d),
                                        monthDiff = Number.Abs(srcMonth - TodayMonth),
                                        swapped  = #date(srcYear, srcDay, srcMonth)
                                    in
                                        if srcDay > 12 and srcMonth <= 12 then swapped
                                        else if monthDiff <= 1 then d
                                        else d
                                else null
                        in
                            result,
                    type date
                }
            }
        ),

    #"Proper Case LiveCash" = Table.TransformColumns(#"Apply Date Fix", {{"Live", Text.Proper, type text}}),

    // 11. Ensure All Headers
    AllHeaders = { /* … same list as before … */ },
    #"Add Missing" = List.Accumulate(AllHeaders, #"Proper Case LiveCash", (state, current) => 
        if List.Contains(Table.ColumnNames(state), current) then state 
        else Table.AddColumn(state, current, each null)
    ),
    #"Selected Columns" = Table.SelectColumns(#"Add Missing", AllHeaders),

    // 12. Sorting
    #"Add Sort Helper" = Table.AddColumn(#"Selected Columns", "SortOrder", each if List.Contains({"Accu", "Accu-g", "Decu", "Decu-g"}, [Struct]) then 1 else 2),
    #"Sorted Output" = Table.Sort(#"Add Sort Helper", {
        {"SortOrder", Order.Ascending},
        {"Customer", Order.Ascending}, 
        {"CCYpair", Order.Ascending}, 
        {"Active Strike", Order.Ascending}, 
        {"FXDC Ref", Order.Ascending}
    }),
    #"Final Cleanup" = Table.RemoveColumns(#"Sorted Output", {"SortOrder"})
in
    #"Final Cleanup"
